import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import UserProvider from "@/providers/userProvider";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[hsl(var(--background-hsl))] flex flex-col min-h-screen`}
      >
        <UserProvider>
          <Navbar />
          <main className="flex-1 flex flex-col items-center justify-center h-full">
            {children}
          </main>
        </UserProvider>
      </body>
    </html>
  );
}
